# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.CharField(max_length=1024, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='album',
            name='img',
            field=models.FileField(upload_to='photos/'),
        ),
    ]
